name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install package and deps
        working-directory: ext/qlib-ext-se
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .
          python -m pip install pytest
      - name: Run tests
        working-directory: ext/qlib-ext-se
        run: pytest -q
